/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlusJNI */

#ifndef _Included_PlusJNI
#define _Included_PlusJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PlusJNI
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_PlusJNI_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
